name: UAT Deploy
on:
    push:
        branches:
            - "uat"
jobs:
    deploy:
        uses: ./.github/workflows/deploy-reusable.yml
        with:
            environment: UAT
            api_base_url: https://www2.zuugle.at
            setup_docker: true
            rebuild_db_structure: true
            refresh_suggestions: true
            use_basic_auth: true
            node_env: production
            command_timeout: 60m
            import_files: true
            pm2_app_name: zuugle_api
        secrets:
            SSH_PRIVATE_KEY: ${{ secrets.UAT_SSH_PRIVATE_KEY }}
            REMOTE_HOST: ${{ secrets.UAT_REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.UAT_REMOTE_USER }}
            REMOTE_PORT: ${{ secrets.UAT_REMOTE_PORT }}
            REMOTE_TARGET: ${{ secrets.UAT_REMOTE_TARGET }}
            DEPLOY_ACCESS: ${{ secrets.DEPLOY_ACCESS }}
            BASIC_AUTH_USER: ${{ secrets.UAT_BASIC_AUTH_USER }}
            BASIC_AUTH_PASSWORD: ${{ secrets.UAT_BASIC_AUTH_PASSWORD }}
