name: PROD Deploy
on:
    push:
        branches:
            - "main"
jobs:
    deploy:
        uses: ./.github/workflows/deploy-reusable.yml
        with:
            environment: PROD
            api_base_url: https://www.zuugle.at
            do_backup: true
        secrets:
            SSH_PRIVATE_KEY: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
            REMOTE_HOST: ${{ secrets.PROD_REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.PROD_REMOTE_USER }}
            REMOTE_PORT: ${{ secrets.PROD_REMOTE_PORT }}
            REMOTE_TARGET: ${{ secrets.PROD_REMOTE_TARGET_API }}
            DEPLOY_ACCESS: ${{ secrets.DEPLOY_ACCESS }}
