import * as React from 'react';
// import Grid from "@mui/material/Grid";
import TourCard from "./TourCard";
import Box from "@mui/material/Box";
import {ScrollMenu} from "react-horizontal-scrolling-menu";
// import {Button} from "@mui/material";
// import {ChevronLeft, ChevronRight} from "@mui/icons-material";
import useMediaQuery from "@mui/material/useMediaQuery";
import {LeftArrow} from "./HorizontalScroll/LeftArrow";
import {RightArrow} from "./HorizontalScroll/RightArrow";

//description
//The ScrollingTourCardContainer.js file contains a React functional component that renders a container for a list of tour cards that can be scrolled horizontally. The component imports several Material UI components, including Box, Grid, and Typography, as well as a custom TourCard component.
// The ScrollingTourCardContainer component takes in several props, including tours (an array of tour objects), title (a string to display as the title of the container), and seeAllLink (a string representing a link to view all the tours).
// The component returns a Box component that contains a Grid component with a row of tour cards. The tour cards are generated by mapping over the tours array and passing each tour object as a prop to the TourCard component. The Grid component has a spacing prop set to 2 to create some space between the tour cards.
// The title of the container is displayed above the tour cards using a Typography component with a variant of h2 and the title prop passed in as the content. If a seeAllLink prop is provided, a Typography component with a variant of subtitle1 and a link to the provided seeAllLink is also displayed below the tour cards.
// The component also includes some custom styles for the container, such as a maxWidth of 1200px, a margin of 0 auto to center the container, and padding of 24px on all sides. Finally, the component exports the ScrollingTourCardContainer function as the default export.

export default function ScrollingTourCardContainer({tours, onSelectTour, loadTourConnections, city}){

    const isMobile = useMediaQuery('(max-width:600px)');

    if(!!isMobile){
        return <Box component="div">
            <Box style={{width: "100%", overflowX: "scroll", whiteSpace: "nowrap", display: "flex", alignItems: "stretch"}}>
                {(!!tours ? tours : []).map((tour,index) => <Box key={index} className={"scrolling-card-box"} style={{display: "block", marginRight: "20px", verticalAlign: "top", marginBottom: "5px"}}>
                    <TourCard onSelectTour={onSelectTour} tour={tour} loadTourConnections={loadTourConnections} city={city}/>
                </Box>)
            }
            </Box>
        </Box>
    }


    return <Box component="div">
        <ScrollMenu LeftArrow={LeftArrow} RightArrow={RightArrow} >
            {
                (!!tours ? tours : []).map(tour => <Card
                    itemId={tour.id}
                    tour={tour}
                    key={tour.id}
                    onSelectTour={onSelectTour}
                    loadTourConnections={loadTourConnections}
                    city={city}
                />)
            }
        </ScrollMenu>
    </Box>
}

function Card({ tour, onSelectTour, loadTourConnections, city }) {
    return (
        <Box
            className={"react-horizontal-scrolling-card"}
            tabIndex={0}
            component="div"
        >
            <TourCard onSelectTour={onSelectTour} tour={tour} loadTourConnections={loadTourConnections} city={city}/>
        </Box>
    );
}

