name: DEV Deploy

on:
  push:
    branches:
      - "dev"

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    secrets:
      DEPLOY_ACCESS: ${{ secrets.DEPLOY_ACCESS }}
      SSH_PRIVATE_KEY: ${{ secrets.UAT_SSH_PRIVATE_KEY }}
      REMOTE_HOST: ${{ secrets.UAT_REMOTE_HOST }}
      REMOTE_USER: ${{ secrets.UAT_REMOTE_USER }}
      REMOTE_TARGET: ${{ secrets.DEV_REMOTE_TARGET }}
