name: PROD Deploy

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      with_backup: true
    secrets:
      DEPLOY_ACCESS: ${{ secrets.DEPLOY_ACCESS }}
      SSH_PRIVATE_KEY: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
      REMOTE_HOST: ${{ secrets.PROD_REMOTE_HOST }}
      REMOTE_USER: ${{ secrets.PROD_REMOTE_USER }}
      REMOTE_TARGET: ${{ secrets.PROD_REMOTE_TARGET_SUCHSEITE }}
      REMOTE_PORT: ${{ secrets.PROD_REMOTE_PORT }}
